apiVersion: 1

datasources:
  - name: PostgreSQL (Чистый берег)
    uid: chistybereg-postgres
    type: postgres
    access: proxy
    url: db:5432
    database: ${GRAFANA_DB_NAME}
    user: grafana_reader
    isDefault: true
    editable: false
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
